from __future__ import annotations

from pathlib import Path

from .models import ProjectSnapshot, now_iso


POLICY_RELATIVE_PATH = Path(".delta-loop") / "POLICY.md"
LOOP_RELATIVE_PATH = Path(".delta-loop") / "LOOP.md"

CATEGORY_NAMES = {
    "loop": "Research loop",
    "checkpoint": "Extra checks",
    "project": "Agent and file boundaries",
    "git": "Git and GitHub",
    "hardware": "Hardware",
    "data": "Data",
    "resources": "Time and resources",
    "temporary": "Temporary limits",
}

WORK_KIND_NAMES = {
    "quick-test": "Quick Test",
    "replicate": "Replicate",
    "literature-review": "Literature review",
    "compare-explanations": "Compare explanations",
    "ablation": "Ablation",
    "full-study": "Full study",
    "research-engineering": "Research engineering",
}


class PolicySyncFailure(ValueError):
    pass


def _line(value: str) -> str:
    return " ".join(value.split())


def _table(value: str) -> str:
    return _line(value).replace("|", "\\|")


def render_policy(workspace: ProjectSnapshot, synced_at: str | None = None) -> str:
    active = next(
        (
            version
            for version in workspace.rules_versions
            if version.id == workspace.active_rules_version_id
        ),
        None,
    )
    timestamp = synced_at or now_iso()
    version_number = active.version if active else 0
    compute = workspace.compute
    compute_location = (
        "Not configured"
        if not compute.configured
        else f"SSH server {compute.name or compute.ssh_host} ({compute.ssh_host})"
        if compute.kind == "ssh"
        else "This computer"
    )
    compute_project = (
        "Not configured"
        if not compute.configured
        else compute.project_path if compute.kind == "ssh" else workspace.root
    )
    lines = [
        "# Active Delta Loop Policy",
        "",
        "<!-- Generated by Delta Loop. Change policy in Delta Loop, not in this file. -->",
        "",
        f"- **Project:** {_line(workspace.name)}",
        f"- **Main question:** {_line(workspace.goal)}",
        f"- **Policy version:** {version_number}",
        f"- **Compute location:** {_line(compute_location)}",
        f"- **Compute project:** {_line(compute_project)}",
        f"- **Written:** {timestamp}",
        "",
        "## How to use this policy",
        "",
        "1. `.delta-loop/LOOP.md` is the complete research loop generated by Delta Loop. No outside supervisor file is required.",
        "2. Read this file at the start of every cycle so the loop has the current idea choices and extra rules.",
        "3. Apply every enabled rule whose `When` and `Applies to` fields match the proposed work.",
        "4. Match the proposed work to the closest way-to-test entry below and follow its `Next work`, guidance, and stop point.",
        "5. Do not select a way to test whose status is `dormant` or `closed`.",
        "6. Copy the applicable rule IDs and matched idea policy into `PLAN.md` before preserving `PLAN.initial.md` and starting a worker. That policy copy cannot change during the run.",
        "7. Treat a matching `Stop only if` field as a hard boundary. Do not turn ordinary uncertainty or a missing preference into an approval request.",
        "8. A rule for one idea may narrow the general policy, but it cannot override a required rule.",
        "9. Start work through Delta Loop so it uses the saved compute location; do not silently move work to another machine.",
        "10. Git rules apply to the research repository at the compute project path. For a remote project, the local Delta Loop folder stores control notes and is not the repository to commit.",
        "",
        "## Research map",
        "",
        "The project may have several high-level questions and a continuing trace through ideas, research work, findings, and revised ideas. Follow the recorded main placements and relationships instead of assuming one fixed tree or stopping at the first experiment.",
        "",
        "| ID | Level | Title | Status |",
        "|---|---|---|---|",
    ]

    level_names = {"question": "Question", "direction": "Idea", "approach": "Work", "finding": "Finding"}
    for node in workspace.nodes:
        lines.append(
            f"| `{_table(node.id)}` | {_table(level_names[node.kind])} | "
            f"{_table(node.title)} | {_table(node.status)} |"
        )
    lines.extend(["", "| From | Relationship | To | Note |", "|---|---|---|---|"])
    nodes_by_id = {node.id: node for node in workspace.nodes}
    for link in workspace.research_links:
        source = nodes_by_id.get(link.source_id)
        target = nodes_by_id.get(link.target_id)
        if source and target:
            lines.append(
                f"| {_table(source.title)} | {_table(link.relationship.replace('-', ' '))} | "
                f"{_table(target.title)} | {_table(link.note or '—')} |"
            )
    if not workspace.research_links:
        lines.append("| — | No relationships recorded | — | — |")
    initialization = workspace.initialization
    if initialization.status == "complete":
        lines.extend(
            [
                "",
                "## Researcher-approved starting setup",
                "",
                f"- **Project understanding:** {_line(initialization.project_understanding)}",
                f"- **Success looks like:** {_line(initialization.success_condition)}",
                f"- **Stop when:** {_line(initialization.stop_condition)}",
                f"- **Budget:** {_line(initialization.budget)}",
                f"- **Agent command permission:** {_line(initialization.permission_mode)}",
                "- **Literature:** Review every new or materially changed hypothesis before empirical work.",
                f"- **Initialization record:** {_line(initialization.initialization_file)}",
                "",
                "### Reusable inputs",
                "",
            ]
        )
        reusable = [*workspace.reference_repos, *initialization.reusable_inputs]
        lines.extend([f"- {_line(item)}" for item in reusable] or ["- None recorded"])
        lines.extend(["", "### Starting constraints", ""])
        lines.extend(
            [f"- {_line(item)}" for item in workspace.setup_constraints]
            or ["- None recorded"]
        )
    lines.extend(["", "## Enabled general rules"])

    enabled = [rule for rule in (active.rules if active else []) if rule.enabled]
    for category in CATEGORY_NAMES:
        category_rules = [rule for rule in enabled if rule.category == category]
        if not category_rules:
            continue
        lines.extend(["", f"### {CATEGORY_NAMES[category]}", ""])
        for rule in category_rules:
            title = "Quick Test" if rule.id == "start-with-small-test" else rule.title
            lines.extend(
                [
                    f"- `{rule.id}` — **{_line(title)}**",
                    f"  - **When:** {_line(rule.when)}",
                    f"  - **Do:** {_line(rule.instruction)}",
                    f"  - **Applies to:** {_line(rule.scope)}",
                ]
            )
            if rule.loop_step_ids:
                lines.append(f"  - **Used in loop steps:** {_line(', '.join(rule.loop_step_ids))}")
            if rule.source_label:
                lines.append(f"  - **Source:** {_line(rule.source_label)}")
            if rule.expires_when:
                lines.append(f"  - **Ends:** {_line(rule.expires_when)}")

    approaches = [node for node in workspace.nodes if node.kind == "approach"]
    directions = {node.id: node for node in workspace.nodes if node.kind == "direction"}
    lines.extend(
        [
            "",
            "## Policy for each way to test an idea",
            "",
            "Match by title and idea. If no entry clearly matches, use the enabled general rules and Quick Test.",
            "",
            "| Way to test | Idea | Status | Next work | Special guidance | Stop only if |",
            "|---|---|---|---|---|---|",
        ]
    )
    for approach in approaches:
        connected_direction_ids = [
            link.source_id for link in workspace.research_links
            if link.target_id == approach.id and link.relationship == "tests"
        ]
        connected_directions = [
            directions[node_id].title for node_id in connected_direction_ids
            if node_id in directions
        ]
        direction = directions.get(approach.parent_id or "")
        idea_names = connected_directions or ([direction.title] if direction else [])
        lines.append(
            "| "
            + " | ".join(
                [
                    _table(approach.title),
                    _table("; ".join(idea_names) if idea_names else "Not linked"),
                    _table(approach.status),
                    _table(WORK_KIND_NAMES.get(approach.next_work_kind, approach.next_work_kind)),
                    _table(approach.agent_guidance or "Use the general policy"),
                    _table(approach.ask_before or "No additional stop"),
                ]
            )
            + " |"
        )

    if not approaches:
        lines.append("| No ways to test an idea recorded | — | — | Quick Test | Use the general policy | No additional stop |")

    lines.extend(
        [
            "",
            "## Precedence",
            "",
            "Required safety rule → matching idea policy → other enabled rules → the active research-loop step.",
            "",
            "Only this active generated file controls future cycles. Policy already sealed into a running plan does not change mid-run.",
            "",
        ]
    )
    return "\n".join(lines)


def render_loop_instructions(workspace: ProjectSnapshot, synced_at: str | None = None) -> str:
    timestamp = synced_at or now_iso()
    active = next(
        (
            version
            for version in workspace.rules_versions
            if version.id == workspace.active_rules_version_id
        ),
        None,
    )
    policy = Path(workspace.root).expanduser().resolve() / POLICY_RELATIVE_PATH
    enabled = [rule for rule in (active.rules if active else []) if rule.enabled]
    loop_rules = [rule for rule in enabled if rule.category == "loop"]
    loop_stages = [rule for rule in loop_rules if rule.loop_level == "stage"]
    loop_steps = [rule for rule in loop_rules if rule.loop_level == "step"]
    other_rules = [rule for rule in enabled if rule.category != "loop"]
    git_rules = [rule for rule in other_rules if rule.category == "git"]
    shared_rules = [rule for rule in other_rules if not rule.loop_step_ids]
    version_number = active.version if active else 0
    compute = workspace.compute
    compute_location = (
        "Not configured"
        if not compute.configured
        else f"SSH server {compute.name or compute.ssh_host} ({compute.ssh_host})"
        if compute.kind == "ssh"
        else "this computer"
    )
    compute_project = (
        "Not configured"
        if not compute.configured
        else compute.project_path if compute.kind == "ssh" else workspace.root
    )

    lines = [
        "# Delta Loop Research Instructions",
        "",
        "<!-- Generated by Delta Loop. Change the loop in Delta Loop, not in this file. -->",
        "",
        "This is the complete active research loop. Do not look for or combine it with another supervisor specification.",
        "",
        f"- **Project:** {_line(workspace.name)}",
        f"- **Main question:** {_line(workspace.goal)}",
        f"- **Policy version:** {version_number}",
        f"- **Written:** {timestamp}",
        f"- **Current idea policy:** {_line(str(policy))}",
        f"- **Approved compute location:** {_line(compute_location)}",
        f"- **Project path on that computer:** {_line(compute_project)}",
        "",
        "## Before starting",
        "",
        "1. Read this file and the current idea policy recorded above.",
        "2. Run `delta context` in a Delta Loop terminal to see the selected idea and current human choices.",
        "3. Run `delta compute show` before planning execution. If no location is configured, report that concrete setup blocker; do not pretend research work ran.",
        "4. If a Git rule is enabled, run `delta git check` and apply Git only to the actual research repository shown there, not Delta Loop's local control folder.",
        "5. If either generated file cannot be read, stop and report the blocker instead of guessing.",
        "",
        "## Research cycle",
        "",
    ]

    if loop_stages:
        for stage_index, stage in enumerate(loop_stages, start=1):
            lines.extend(
                [
                    f"### {stage_index}. {_line(stage.title)}",
                    "",
                    f"- **Purpose:** {_line(stage.instruction)}",
                    f"- **Starts:** {_line(stage.when)}",
                    f"- **Stage ID:** `{stage.id}`",
                    "",
                ]
            )
            children = [step for step in loop_steps if step.loop_parent_id == stage.id]
            if not children:
                lines.extend(["This stage currently has no smaller steps.", ""])
                continue
            for step_index, step in enumerate(children, start=1):
                lines.extend(
                    [
                        f"#### {stage_index}.{step_index} {_line(step.title)}",
                        "",
                        f"- **When:** {_line(step.when)}",
                        f"- **Do:** {_line(step.instruction)}",
                        f"- **Step ID:** `{step.id}`",
                        "",
                    ]
                )
                related_rules = [rule for rule in other_rules if step.id in rule.loop_step_ids]
                if related_rules:
                    lines.extend(["##### Details for this step", ""])
                    for rule in related_rules:
                        lines.extend(
                            [
                                f"- `{rule.id}` — **{_line(rule.title)}** ({CATEGORY_NAMES[rule.category]})",
                                f"  - **When:** {_line(rule.when)}",
                                f"  - **Do:** {_line(rule.instruction)}",
                            ]
                        )
                        if rule.source_label:
                            lines.append(f"  - **Source:** {_line(rule.source_label)}")
                    lines.append("")
    else:
        lines.extend(["No main research stage is active. Report this concrete policy blocker; research cannot run until a stage is restored.", ""])

    lines.extend(["## Checks and limits that apply across the loop", ""])
    for rule in shared_rules:
        lines.extend(
            [
                f"- `{rule.id}` — **{_line(rule.title)}**",
                f"  - When: {_line(rule.when)}",
                f"  - Do: {_line(rule.instruction)}",
                f"  - Applies to: {_line(rule.scope)}",
            ]
        )
        if rule.source_label:
            lines.append(f"  - Source: {_line(rule.source_label)}")
        if rule.expires_when:
            lines.append(f"  - Ends: {_line(rule.expires_when)}")
    if not shared_rules:
        lines.append("- No shared check or limit is active.")

    lines.extend(
        [
            "",
            "## Idea choice and worker handoff",
            "",
            "Use the research map to keep the main question, ideas, ways to test them, and their active or parked state distinct. Match the selected work to the closest entry in the current idea policy. Do not choose parked or closed work.",
            "",
            "Before preserving `PLAN.initial.md`, add a `## Delta Loop Policy` section to PLAN.md containing:",
            "",
            "- active policy version",
            "- selected idea and way to test it",
            "- requested next-work type",
            "- applicable rule IDs",
            "- special instructions",
            "- any hard condition that would make the work stop",
            "",
            "Copy that exact section into the worker handoff. The running work follows the sealed copy even if the policy changes later.",
            "",
            "## When to stop",
            "",
            "Do not stop for ordinary scientific choices, plan approval, implementation choices, result interpretation, map updates, or promotion to the next investigation stage. When uncertain, run the cheapest safe test that can reduce the uncertainty. If one path is blocked, record it and continue with another eligible path.",
            "",
            "Stop only when a saved success or stop condition applies, the remaining budget or hardware limit prevents useful work, the next necessary action is prohibited or materially irreversible, required access is unavailable, or no safe useful test remains anywhere in the active research map.",
            "",
            "## Persistent terminal",
            "",
            "When `DELTA_LOOP_WORKSPACE_ID` is set, continue immediate cycles in this same supervisor terminal. A bounded worker may be started for the sealed work, but do not start a fresh supervisor merely to continue the loop.",
            "",
            "## Which rule wins",
            "",
            "Required safety rule → matching idea policy → other enabled rules → the active research-loop step.",
            "",
            (
                "Push only at the exact point described by an enabled Git rule. If pushing is not authorized, "
                "skip the push and continue the research loop. No policy rule by itself authorizes publishing "
                "elsewhere, deleting data, spending money, or another outside side effect."
                if git_rules
                else "No Git rule is enabled. Do not commit or push; keep researching without those Git actions. Publishing elsewhere, deleting data, spending money, or another outside side effect is prohibited."
            ),
            "",
        ]
    )
    return "\n".join(lines)


def sync_policy(workspace: ProjectSnapshot) -> Path:
    root = Path(workspace.root).expanduser().resolve()
    if not root.is_dir():
        raise PolicySyncFailure(f"Research project directory does not exist: {root}")
    policy_path = root / POLICY_RELATIVE_PATH
    loop_path = root / LOOP_RELATIVE_PATH
    timestamp = now_iso()
    try:
        policy_path.parent.mkdir(parents=True, exist_ok=True)
        temporary = policy_path.with_suffix(".tmp")
        temporary.write_text(render_policy(workspace, timestamp), encoding="utf-8")
        temporary.replace(policy_path)
        loop_temporary = loop_path.with_suffix(".tmp")
        loop_temporary.write_text(render_loop_instructions(workspace, timestamp), encoding="utf-8")
        loop_temporary.replace(loop_path)
    except OSError as exc:
        raise PolicySyncFailure(f"Could not write active policy to {policy_path}: {exc}") from exc
    workspace.policy_file = str(policy_path)
    workspace.loop_file = str(loop_path)
    workspace.policy_synced_at = timestamp
    return policy_path
