from __future__ import annotations

from pathlib import Path

from .models import ProjectSnapshot, now_iso


POLICY_RELATIVE_PATH = Path(".delta-loop") / "POLICY.md"
LOOP_RELATIVE_PATH = Path(".delta-loop") / "LOOP.md"

CATEGORY_NAMES = {
    "loop": "Research loop",
    "checkpoint": "Extra checks",
    "project": "Project rules",
    "git": "Git and GitHub",
    "hardware": "Hardware",
    "data": "Data",
    "resources": "Time and resources",
    "temporary": "Temporary limits",
}

WORK_KIND_NAMES = {
    "quick-test": "Quick Test",
    "replicate": "Replicate",
    "literature-review": "Literature review",
    "compare-explanations": "Compare explanations",
    "ablation": "Ablation",
    "full-study": "Full study",
    "research-engineering": "Research engineering",
}


class PolicySyncFailure(ValueError):
    pass


def _line(value: str) -> str:
    return " ".join(value.split())


def _table(value: str) -> str:
    return _line(value).replace("|", "\\|")


def render_policy(workspace: ProjectSnapshot, synced_at: str | None = None) -> str:
    active = next(
        (
            version
            for version in workspace.rules_versions
            if version.id == workspace.active_rules_version_id
        ),
        None,
    )
    timestamp = synced_at or now_iso()
    version_number = active.version if active else 0
    lines = [
        "# Active Delta Loop Policy",
        "",
        "<!-- Generated by Delta Loop. Change policy in Delta Loop, not in this file. -->",
        "",
        f"- **Project:** {_line(workspace.name)}",
        f"- **Main question:** {_line(workspace.goal)}",
        f"- **Policy version:** {version_number}",
        f"- **Written:** {timestamp}",
        f"- **delta-research source:** {_line(workspace.harness.source_url)}",
        f"- **delta-research checkout:** {_line(workspace.harness.path or 'Not found')}",
        f"- **delta-research revision:** {_line(workspace.harness.revision or 'Unknown')}",
        "",
        "## How the research loop must use this file",
        "",
        "1. Read this file at the start of every supervisor cycle, before choosing the next delta.",
        "   Follow the delta-research supervisor contract from the checkout recorded above; this file supplies the active researcher choices that contract must apply.",
        "2. Apply every enabled general rule whose `When` and `Applies to` fields match the proposed work.",
        "3. Match the proposed delta to the closest way-to-test entry below and follow its `Next work`, guidance, and stop point.",
        "4. Do not select a way to test whose status is `dormant` or `closed`.",
        "5. Copy the applicable rule IDs and the matched way-to-test policy into `PLAN.md` before preserving `PLAN.initial.md` and spawning a worker. The Policy section cannot be amended during that run.",
        "6. If a matching rule or `Ask before` field requires human input, trigger the `POLICY` interrupt before planning or starting that action.",
        "7. A rule for one idea may narrow the general policy, but it cannot override a required rule.",
        "",
        "## Enabled general rules",
    ]

    enabled = [rule for rule in (active.rules if active else []) if rule.enabled]
    for category in CATEGORY_NAMES:
        category_rules = [rule for rule in enabled if rule.category == category]
        if not category_rules:
            continue
        lines.extend(["", f"### {CATEGORY_NAMES[category]}", ""])
        for rule in category_rules:
            title = "Quick Test" if rule.id == "start-with-small-test" else rule.title
            lines.extend(
                [
                    f"- `{rule.id}` — **{_line(title)}**",
                    f"  - **When:** {_line(rule.when)}",
                    f"  - **Do:** {_line(rule.instruction)}",
                    f"  - **Applies to:** {_line(rule.scope)}",
                ]
            )
            if rule.expires_when:
                lines.append(f"  - **Ends:** {_line(rule.expires_when)}")

    approaches = [node for node in workspace.nodes if node.kind == "approach"]
    directions = {node.id: node for node in workspace.nodes if node.kind == "direction"}
    lines.extend(
        [
            "",
            "## Policy for each way to test an idea",
            "",
            "Match by title and idea. If no entry clearly matches, use the enabled general rules and Quick Test.",
            "",
            "| Way to test | Idea | Status | Next work | Special guidance | Ask before |",
            "|---|---|---|---|---|---|",
        ]
    )
    for approach in approaches:
        direction = directions.get(approach.parent_id or "")
        lines.append(
            "| "
            + " | ".join(
                [
                    _table(approach.title),
                    _table(direction.title if direction else "Not linked"),
                    _table(approach.status),
                    _table(WORK_KIND_NAMES.get(approach.next_work_kind, approach.next_work_kind)),
                    _table(approach.agent_guidance or "Use the general policy"),
                    _table(approach.ask_before or "Use the general extra checks"),
                ]
            )
            + " |"
        )

    if not approaches:
        lines.append("| No ways to test an idea recorded | — | — | Quick Test | Use the general policy | Use the general extra checks |")

    lines.extend(
        [
            "",
            "## Precedence",
            "",
            "Required safety rule → matching idea policy → other enabled general rules → default delta-research behavior.",
            "",
            "Only this active generated file controls future cycles. Policy already sealed into a running plan does not change mid-run.",
            "",
        ]
    )
    return "\n".join(lines)


def render_loop_instructions(workspace: ProjectSnapshot, synced_at: str | None = None) -> str:
    timestamp = synced_at or now_iso()
    supervisor = (
        Path(workspace.harness.path) / "templates" / "SUPERVISOR.md"
        if workspace.harness.path
        else Path("delta-research/templates/SUPERVISOR.md")
    )
    policy = Path(workspace.root).expanduser().resolve() / POLICY_RELATIVE_PATH
    return "\n".join(
        [
            "# Delta Loop Research Instructions",
            "",
            "<!-- Generated by Delta Loop. Do not edit this file by hand. -->",
            "",
            f"- **Project:** {_line(workspace.name)}",
            f"- **Written:** {timestamp}",
            f"- **Base research loop:** {_line(str(supervisor))}",
            f"- **Researcher policy:** {_line(str(policy))}",
            f"- **Base source:** {_line(workspace.harness.source_url)}",
            f"- **Base revision:** {_line(workspace.harness.revision or 'Unknown')}",
            "",
            "## Read in this order",
            "",
            "1. Read the base delta-research supervisor file recorded above.",
            "2. Read the active researcher policy recorded above.",
            "3. Read `STATE.md`, `INFRA.md` when present, and the other project records required by the base loop.",
            "4. Run `delta context` when this is a Delta Loop terminal so the selected idea and current human choices are visible.",
            "",
            "If the base supervisor or active policy cannot be read, stop with `BLOCKER`; do not guess the research loop.",
            "",
            "## What Delta Loop adds",
            "",
            "- Use the research map to keep the main question, ideas, ways to test them, and their active or parked state distinct.",
            "- Apply the active general rules and the matching idea policy before choosing or scoping work.",
            "- Do not select a way to test an idea that Delta Loop marks dormant or closed.",
            "- Use `Next work` to choose the requested work size and type. A Quick Test stays the smallest useful discriminating test.",
            "- Trigger the `POLICY` interrupt before any action covered by an `Ask before` field or matching approval rule.",
            "- Keep progress reporting short and spend the work budget on research outputs rather than rehearsing or retesting the harness.",
            "",
            "## Plan and worker handoff",
            "",
            "Before preserving `PLAN.initial.md`, add a `## Delta Loop Policy` section to the live plan with:",
            "",
            "- active policy version",
            "- matched way to test",
            "- requested next work",
            "- applicable rule IDs",
            "- special guidance",
            "- ask-before boundary",
            "",
            "That section is fixed for the run even if other execution-only fields in the live plan are amended. Include the exact same section in the worker handoff. The worker follows the sealed copy, not later policy changes.",
            "",
            "## Persistent supervision",
            "",
            "When `DELTA_LOOP_WORKSPACE_ID` is set, remain in the same persistent terminal for immediate cycles. Do not launch or schedule a fresh Codex process merely to continue the loop. A bounded worker may still be launched for an approved, sealed piece of work.",
            "",
            "## Precedence",
            "",
            "Base scientific, ownership, safety, and explicit Git-authorization contracts → required Delta Loop safety rules → matching idea policy → other enabled Delta Loop rules → base defaults.",
            "",
            "The generated policy does not by itself authorize pushing, publishing, deleting data, or another external side effect.",
            "",
        ]
    )


def sync_policy(workspace: ProjectSnapshot) -> Path:
    root = Path(workspace.root).expanduser().resolve()
    if not root.is_dir():
        raise PolicySyncFailure(f"Research project directory does not exist: {root}")
    policy_path = root / POLICY_RELATIVE_PATH
    loop_path = root / LOOP_RELATIVE_PATH
    timestamp = now_iso()
    try:
        policy_path.parent.mkdir(parents=True, exist_ok=True)
        temporary = policy_path.with_suffix(".tmp")
        temporary.write_text(render_policy(workspace, timestamp), encoding="utf-8")
        temporary.replace(policy_path)
        loop_temporary = loop_path.with_suffix(".tmp")
        loop_temporary.write_text(render_loop_instructions(workspace, timestamp), encoding="utf-8")
        loop_temporary.replace(loop_path)
    except OSError as exc:
        raise PolicySyncFailure(f"Could not write active policy to {policy_path}: {exc}") from exc
    workspace.policy_file = str(policy_path)
    workspace.loop_file = str(loop_path)
    workspace.policy_synced_at = timestamp
    return policy_path
