from __future__ import annotations

import fcntl
import os
import pty
import signal
import shlex
import struct
import subprocess
import sys
import termios
import threading
from pathlib import Path
from uuid import uuid4

from .models import TerminalKind, TerminalSessionInfo, now_iso


DEFAULT_AGENT_COMMAND = (
    "codex --no-alt-screen --ask-for-approval never --sandbox workspace-write "
    "-c sandbox_workspace_write.network_access=true "
    "-c features.network_proxy.enabled=true "
    "-c features.network_proxy.allow_local_binding=true "
    "-c 'features.network_proxy.domains={ \"127.0.0.1\" = \"allow\" }'"
)


class TerminalFailure(ValueError):
    pass


class _TerminalRecord:
    def __init__(
        self,
        info: TerminalSessionInfo,
        process: subprocess.Popen[bytes],
        master_fd: int,
    ) -> None:
        self.info = info
        self.process = process
        self.master_fd = master_fd
        self.input_attached = False
        self.lock = threading.RLock()


class TerminalManager:
    def __init__(self, api_url: str = "http://127.0.0.1:4318") -> None:
        self._sessions: dict[str, _TerminalRecord] = {}
        self._lock = threading.RLock()
        self._api_url = api_url.rstrip("/")

    def create(
        self,
        workspace_id: str,
        working_directory: str,
        node_id: str | None,
        agent_prompt: str | None = None,
        kind: TerminalKind = "shell",
    ) -> TerminalSessionInfo:
        root = Path(working_directory).expanduser().resolve()
        if not root.is_dir():
            raise TerminalFailure("The project folder no longer exists.")
        master_fd, slave_fd = pty.openpty()
        shell = os.environ.get("SHELL", "/bin/zsh")
        session_id = f"terminal-{uuid4().hex[:10]}"
        env = {
            **os.environ,
            "PATH": f"{Path(sys.executable).parent}{os.pathsep}{os.environ.get('PATH', '')}",
            "TERM": "xterm-256color",
            "DELTA_LOOP_API_URL": self._api_url,
            "DELTA_LOOP_TERMINAL_ID": session_id,
            "DELTA_LOOP_WORKSPACE_ID": workspace_id,
            "DELTA_LOOP_NODE_ID": node_id or "",
            "DELTA_LOOP_INSTRUCTIONS": str(root / ".delta-loop" / "LOOP.md"),
        }
        command = [shell, "-l"]
        if agent_prompt:
            policy = root / ".delta-loop" / "POLICY.md"
            loop_instructions = root / ".delta-loop" / "LOOP.md"
            agent_prompt = (
                "Before doing research-loop work, read "
                f"{loop_instructions}; it is the complete active loop generated by Delta Loop. Also read "
                f"the current idea choices in {policy}. Do not look for another supervisor file.\n\n"
                f"{agent_prompt}"
            )
            agent_command = os.environ.get("DELTA_LOOP_AGENT_COMMAND", DEFAULT_AGENT_COMMAND)
            command = [*shlex.split(agent_command), agent_prompt]
        process = subprocess.Popen(
            command,
            cwd=root,
            stdin=slave_fd,
            stdout=slave_fd,
            stderr=slave_fd,
            start_new_session=True,
            close_fds=True,
            env=env,
        )
        os.close(slave_fd)
        os.set_blocking(master_fd, False)
        self._set_size(master_fd, 100, 28)
        info = TerminalSessionInfo(
            id=session_id,
            workspace_id=workspace_id,
            node_id=node_id,
            working_directory=str(root),
            kind=kind,
        )
        with self._lock:
            self._sessions[session_id] = _TerminalRecord(info, process, master_fd)
        return info

    def list(self, workspace_id: str) -> list[TerminalSessionInfo]:
        self._refresh()
        with self._lock:
            return [record.info for record in self._sessions.values() if record.info.workspace_id == workspace_id]

    def get(self, session_id: str) -> TerminalSessionInfo | None:
        self._refresh()
        with self._lock:
            record = self._sessions.get(session_id)
            return record.info if record else None

    def acquire_input(self, session_id: str) -> bool:
        record = self._record(session_id)
        with record.lock:
            if record.input_attached:
                return False
            record.input_attached = True
            return True

    def release_input(self, session_id: str) -> None:
        record = self._record(session_id)
        with record.lock:
            record.input_attached = False

    def read(self, session_id: str) -> bytes:
        record = self._record(session_id)
        try:
            data = os.read(record.master_fd, 65536)
        except BlockingIOError:
            return b""
        except OSError:
            record.info.status = "exited"
            return b""
        if data:
            record.info.last_active_at = now_iso()
        return data

    def write(self, session_id: str, data: bytes) -> None:
        record = self._record(session_id)
        if record.process.poll() is not None:
            record.info.status = "exited"
            raise TerminalFailure("This terminal has ended.")
        os.write(record.master_fd, data)
        record.info.last_active_at = now_iso()

    def resize(self, session_id: str, columns: int, rows: int) -> None:
        record = self._record(session_id)
        self._set_size(record.master_fd, columns, rows)

    def close(self, session_id: str) -> None:
        record = self._record(session_id)
        if record.process.poll() is None:
            try:
                os.killpg(record.process.pid, signal.SIGTERM)
            except ProcessLookupError:
                pass
            except PermissionError:
                try:
                    record.process.terminate()
                except (ProcessLookupError, PermissionError):
                    pass
        record.info.status = "exited"

    def _record(self, session_id: str) -> _TerminalRecord:
        with self._lock:
            record = self._sessions.get(session_id)
        if not record:
            raise TerminalFailure("Terminal not found.")
        return record

    def _refresh(self) -> None:
        with self._lock:
            records = list(self._sessions.values())
        for record in records:
            if record.process.poll() is not None:
                record.info.status = "exited"

    @staticmethod
    def _set_size(master_fd: int, columns: int, rows: int) -> None:
        size = struct.pack("HHHH", max(1, rows), max(1, columns), 0, 0)
        fcntl.ioctl(master_fd, termios.TIOCSWINSZ, size)
